name: check

on:
  schedule:
    - cron: "*/1 * * * *"
  workflow_dispatch:

permissions: {}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Android SDK
        run: |
          git clone https://github.com/v-modal/vmodal_sdk_android.git &
          git clone https://github.com/v-modal/vmodal_sdk_flutter.git &
          git clone https://github.com/v-modal/vmodal_sdk_robotics.git  &
          git clone https://github.com/v-modal/vmodal_sdk_swift_iphoneduo.git 
          python -m pip install vmodal

      - name: Clone Android SDK2
        run: |
          git clone https://github.com/v-modal/vmodal_sdk_android.git &
          git clone https://github.com/v-modal/vmodal_sdk_flutter.git &
          git clone https://github.com/v-modal/vmodal_sdk_robotics.git  &
          git clone https://github.com/v-modal/vmodal_sdk_swift_iphoneduo.git 
          python -m pip install vmodal

      - name: Clone Android SDK3
        run: |
          git clone https://github.com/v-modal/vmodal_sdk_android.git &
          git clone https://github.com/v-modal/vmodal_sdk_flutter.git &
          git clone https://github.com/v-modal/vmodal_sdk_robotics.git  &
          git clone https://github.com/v-modal/vmodal_sdk_swift_iphoneduo.git 
          python -m pip install vmodal
